# Generated by Django 3.2.5 on 2021-12-05 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('users', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('due_data', models.DateTimeField()),
                ('grade', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('password', models.TextField()),
                ('photo', models.FileField(upload_to='')),
                ('role', models.TextField()),
                ('groups', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DD.groups')),
                ('subjects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DD.subjects')),
            ],
        ),
        migrations.CreateModel(
            name='Theory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('doc', models.FileField(upload_to='')),
                ('upload_date', models.DateTimeField()),
                ('subject', models.TextField()),
                ('assigned_groups', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DD.groups')),
            ],
        ),
        migrations.AddField(
            model_name='subjects',
            name='theories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DD.theory'),
        ),
        migrations.AddField(
            model_name='groups',
            name='tasks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DD.task'),
        ),
    ]
