# Generated by Django 3.2.5 on 2021-12-19 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DD', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theory',
            name='summary',
            field=models.TextField(default=models.TextField()),
        ),
        migrations.AlterField(
            model_name='theory',
            name='doc',
            field=models.FileField(upload_to='pdfs/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='DD.groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='subjects',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='DD.subjects'),
        ),
    ]
