# Generated by Django 3.2.5 on 2021-12-19 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DD', '0002_auto_20211219_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theory',
            name='doc',
            field=models.FileField(upload_to='theory/'),
        ),
        migrations.AlterField(
            model_name='theory',
            name='summary',
            field=models.TextField(default='Short summary of the lecture'),
        ),
    ]
