# Generated by Django 3.2.5 on 2021-12-20 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DD', '0003_auto_20211219_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('file', models.FileField(upload_to='practice/')),
                ('subjects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects_practice', to='DD.subjects')),
            ],
        ),
    ]
