# Generated by Django 3.2.5 on 2021-12-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DD', '0004_practice'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='description',
            field=models.TextField(default='Short summary'),
        ),
    ]
